name: easy_isolate
description: An abstraction of the Isolate to make it easier to use, and with a more concise api
version: 0.0.1
homepage: https://www.britto.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
